name: Pull from Dune

on:
  workflow_dispatch: # This lets you run it manually

jobs:
  pull:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: USDC-Dashboard

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install requirements
        run: pip install -r requirements.txt

      - name: Pull queries from Dune
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        run: python -u scripts/pull_from_dune.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update queries from Dune" || echo "No changes to commit"
          git push
